version: '2'
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:etc/nginx/conf.d"
    links:
      - express

  express:
    image: node:8
    container_name: express
    hostname: express
    volumes:
      - ".:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "8080:8080"
